version: '3.1'
services:
    jenkins:
        container_name: jenkins_master
        build: jenkins/master/
        ports:
            - '8080:8080'
            - '50000:50000'
        # image: localhost:5000/jenkins
    jenkins-slave:
        container_name: jenkins-slave
        build: jenkins/slave/
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        # image: localhost:5000/jenkins-slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins
    node-app:
        container_name: jenkins-docker-node-webapp
        build: app/
        ports:
            - '7010:8080'
